In [1]:
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Flatten
import numpy as np
import pandas as pd
import matplotlib
from sklearn.model_selection import train_test_split

In [46]:
print(tf.__version__)
import warnings
warnings.filterwarnings('ignore')

2.0.0-rc0


In [29]:
#click here for data shttps://www.kaggle.com/aakash50897/churn-modellingcsv
ds = pd.read_csv("Churn_Modelling.csv")
ds.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [30]:
x= ds.drop(labels=['RowNumber','CustomerId','Surname','Exited'],axis=1)
y= ds['Exited']

In [31]:
x.head()

CreditScore Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619    France  Female   42       2       0.00              1   
1          608     Spain  Female   41       1   83807.86              1   
2          502    France  Female   42       8  159660.80              3   
3          699    France  Female   39       1       0.00              2   
4          850     Spain  Female   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [32]:
y.head()

0    1
1    0
2    1
3    0
4    0
Name: Exited, dtype: int64

In [33]:
from sklearn.preprocessing import LabelEncoder
label1 = LabelEncoder()
x['Geography'] = label1.fit_transform(x['Geography'])
label1 = LabelEncoder()
x['Gender'] = label1.fit_transform(x['Gender'])

In [34]:
x.head()

CreditScore  Geography  Gender  Age  Tenure    Balance  NumOfProducts  \
0          619          0       0   42       2       0.00              1   
1          608          2       0   41       1   83807.86              1   
2          502          0       0   42       8  159660.80              3   
3          699          0       0   39       1       0.00              2   
4          850          2       0   43       2  125510.82              1   

   HasCrCard  IsActiveMember  EstimatedSalary  
0          1               1        101348.88  
1          0               1        112542.58  
2          1               0        113931.57  
3          0               0         93826.63  
4          1               1         79084.10

In [36]:
x=pd.get_dummies(x,columns=['Geography'],drop_first=True)
#convert the catagorical data ,onehot encoder is also used
x.head()

CreditScore  Gender  Age  Tenure    Balance  NumOfProducts  HasCrCard  \
0          619       0   42       2       0.00              1          1   
1          608       0   41       1   83807.86              1          0   
2          502       0   42       8  159660.80              3          1   
3          699       0   39       1       0.00              2          0   
4          850       0   43       2  125510.82              1          1   

   IsActiveMember  EstimatedSalary  Geography_1  Geography_2  
0               1        101348.88            0            0  
1               1        112542.58            0            1  
2               0        113931.57            0            0  
3               0         93826.63            0            0  
4               1         79084.10            0            1

In [37]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=0,stratify=y)

In [38]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [39]:
x_train

array([[-1.24021723, -1.09665089,  0.77986083, ...,  1.64099027,
        -0.57812007, -0.57504086],
       [ 0.75974873,  0.91186722, -0.27382717, ..., -1.55587522,
         1.72974448, -0.57504086],
       [-1.72725557, -1.09665089, -0.9443559 , ...,  1.1038111 ,
        -0.57812007, -0.57504086],
       ...,
       [-0.51484098,  0.91186722,  0.87565065, ..., -1.01507508,
         1.72974448, -0.57504086],
       [ 0.73902369, -1.09665089, -0.36961699, ..., -1.47887193,
        -0.57812007, -0.57504086],
       [ 0.95663657,  0.91186722, -1.32751517, ...,  0.50945854,
        -0.57812007,  1.73900686]])

In [48]:
#build Ann
model = Sequential()
model.add(Dense(x.shape[1],activation='relu',input_dim=x.shape[1])) 
model.add(Dense(128,activation='relu')) # for the i/p layer 128 are 
model.add(Dense(1,activation='sigmoid')) # for the o/p

In [49]:
x.shape[1] #if loss funtion is not decrese thenn the model is no overfit

11

In [50]:
#compile the model
model.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

In [51]:
model.fit(x_train,y_train.to_numpy(),batch_size=10,epochs=10,verbose=1)

Train on 8000 samples
Epoch 1/10
8000/8000 [==============================] - 2s 211us/sample - loss: 0.4583 - accuracy: 0.8012
Epoch 2/10
8000/8000 [==============================] - 1s 164us/sample - loss: 0.3973 - accuracy: 0.8384
Epoch 3/10
8000/8000 [==============================] - 1s 144us/sample - loss: 0.3613 - accuracy: 0.8522
Epoch 4/10
8000/8000 [==============================] - 1s 138us/sample - loss: 0.3471 - accuracy: 0.8577
Epoch 5/10
8000/8000 [==============================] - 1s 155us/sample - loss: 0.3423 - accuracy: 0.8559
Epoch 6/10
8000/8000 [==============================] - 1s 147us/sample - loss: 0.3386 - accuracy: 0.8600
Epoch 7/10
8000/8000 [==============================] - 1s 129us/sample - loss: 0.3350 - accuracy: 0.8611
Epoch 8/10
8000/8000 [==============================] - 1s 126us/sample - loss: 0.3332 - accuracy: 0.8637
Epoch 9/10
8000/8000 [==============================] - 1s 158us/sample - loss: 0.3312 - accuracy: 0.8634
Epoch 10/10
8000/8000 [=

In [55]:
y_pred = model.predict_classes(x_test)
y_pred

array([[0],
       [0],
       [0],
       ...,
       [0],
       [1],
       [0]])

In [53]:
y_test

1344    1
8167    0
4747    0
5004    1
3124    1
       ..
9107    0
8249    0
8337    0
6279    1
412     0
Name: Exited, Length: 2000, dtype: int64

In [57]:
model.evaluate(x_test,y_test.to_numpy())

2000/1 [================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[0.35579281497001647, 0.856]

In [60]:
from sklearn.metrics import confusion_matrix,accuracy_score
confusion_matrix(y_test,y_pred)


array([[1550,   43],
       [ 245,  162]], dtype=int64)

In [61]:
accuracy_score(y_test,y_pred)

0.856